sudo: false
language: java
cache:
  directories:
    - "$HOME/.cache"
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - carlos.gavidia@pucp.edu.pe
    on_success: change
    on_failure: always